language: python
python:
 - "2.7"
before_install:
  - pip install codecov
install: 
 - pip install -r requirements.txt
script:
 - py.test rss-generator.py
 - py.test --cov
after_success: 
 - coveralls 
 - bash <(curl -s https://codecov.io/bash)
